### ISSUE TITLE
Cilium Image

### ISSUE THREAD

**Issue by tgeek77** [thkukuk/kubic-control#1]
Hi Thorsten,

I'm not sure if you want bugs for this here or in bugzilla, but I found one:

Command I ran:

kubicctl init --pod-network cilum

Error:

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m59s                  default-scheduler  Successfully assigned kube-system/cilium-2mrjh to worker1
  Normal   Pulling    2m21s (x4 over 3m52s)  kubelet, worker1   Pulling image "registry.opensuse.org/devel/kubic/containers/container/kubic/cilium-init:1.4"
  Warning  Failed     2m21s (x4 over 3m51s)  kubelet, worker1   Failed to pull image "registry.opensuse.org/devel/kubic/containers/container/kubic/cilium-init:1.4": rpc error: code = Unknown desc = Error reading manifest 1.4 in registry.opensuse.org/devel/kubic/containers/container/kubic/cilium-init: manifest unknown
  Warning  Failed     2m21s (x4 over 3m51s)  kubelet, worker1   Error: ErrImagePull
  Normal   BackOff    2m7s (x6 over 3m51s)   kubelet, worker1   Back-off pulling image "registry.opensuse.org/devel/kubic/containers/container/kubic/cilium-init:1.4"
  Warning  Failed     114s (x7 over 3m51s)   kubelet, worker1   Error: ImagePullBackOff
```

According to registry.opensuse.org, the image should now be registry.opensuse.org/opensuse/factory/totest/containers/kubic/cilium-init:1.5 not 1.4

**Comment by thkukuk** [comment]
@mrostecki this is a problem of https://github.com/kubic-project/k8s-manifests/blob/master/cilium.yaml, which does not get updated if we update cilium.
I would propose to create a cilium sub-package cilium-k8s-yaml, which contains this file and adjusts the version number in the spec file. Or any other ideas?

**Comment by vadorovsky** [comment]
@thkukuk Creating a cilium sub-package will solve the problem of updating a version, but then how we are going to host the yaml file? Or we are going to include *-yaml packages in the `kubeadm` pattern?

**Comment by thkukuk** [comment]
On Fri, May 10, Michal Rostecki wrote:

> @thkukuk Creating a cilium sub-package will solve the problem of updating a
> version, but then how we are going to host the yaml file? Or we are going to
> include *-yaml packages in the kubeadm pattern?

Yes, that's what we are already doing and what we plan to do for the
containers in the devel queue.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & MicroOS
SUSE Linux GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nuernberg)

**Comment by vadorovsky** [comment]
>Yes, that's what we are already doing

With which image are we already doing that? I would like to look for an example. :)

**Comment by thkukuk** [comment]
On Fri, May 10, Michal Rostecki wrote:

>     Yes, that's what we are already doing
> 
> With which image are we already doing that? I would like to look for an
> example. :)

https://build.opensuse.org/package/view_file/openSUSE:Factory/kured/kured.spec?expand=1
https://build.opensuse.org/package/view_file/openSUSE:Factory/metallb/metallb.spec?expand=1
https://build.opensuse.org/package/view_file/home:kukuk:container/flannel/flannel.spec?expand=1

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & MicroOS
SUSE Linux GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nuernberg)

**Comment by vadorovsky** [comment]
The overall status of Cilium is that I updated it to 1.5.1 and I created the cilium-k8s-yaml package in devel project:

https://build.opensuse.org/package/view_file/devel:kubic/cilium/cilium.spec?expand=1

But before updating Cilium, I didn't realize that iproute2 patches (for BPF programs templating in `tc`) we need for Cilium 1.5.x were not available in Factory... The following SR to be accepted to make Cilium 1.5.x work:

https://build.opensuse.org/request/show/702651

As soon as updated iproute2 will be available in Tumbleweed, I'm going to test the manifest and if it will work, push it to Factory too. The whole Cilium deployment already worked for me, but Cilium couldn't load BPF programs, due to outdated iproute2 package.
