### ISSUE TITLE
[FEATURE] - Add a way to centralise kube-api configuration

### ISSUE THREAD

**Issue by 0pendev** [thkukuk/kubic-control#18]
It would be great to add a simple way to deploy the same kube-api configuration on all masters (for exemple when adding audit logging).

**Comment by thkukuk** [comment]
Could you give an example what you mean with this?
In the end we have that already: you can execute a command with salt on all masters (and only the masters).

**Comment by 0pendev** [comment]
For example, if I want to add audit loggin, I need to do the following on each nodes : 

1. Add the file /etc/kubernetes/audit-policies/policy.yaml
2. Update /etc/kubernetes/manifests/kube-apiserver.yaml

If I understand what you are saying I should use salt to do the following and not kubicctl ?

I'm not sure how much modifying the kube-apiserver.yaml might break kubic on the long run and that is why I thought it might be interesting to manage it with kubicd/kubicctl.

**Comment by thkukuk** [comment]
kubic-control only uses standard kubeadm/kubectl calls and the only local data are the hashes of the third party yaml files to find out, if something needs to be updated.
It doesn't store any internal kubernetes details.
So distributing files and doing changes on a set of machines is a classical "salt" usecase.
Only if you need to adjust kubeadm calls during setup of the cluster, this should go into kubic-control.
kubic-control should be an easy way to bootstrap kubernetes and update it, but not a full blown kubernetes configuration management tool.

**Comment by 0pendev** [comment]
I don't need it during the setup so I'll simply use salt as you suggested. Thanks for the answer.
