### ISSUE TITLE
--adv-addr not working

### ISSUE THREAD

**Issue by schmitch** [thkukuk/kubic-control#21]
Hello, I tried to play with kubicctl and kube-vip.
Unfortunatly I'm hard stuck that I can't set my `--adv-addr` (full command: `kubicctl init --multi-master 192.168.179.60 --adv-addr 192.168.179.61`):

```
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="Executing /usr/bin/rpm: [rpm -q --qf '%{VERSION}' kubernetes-kubeadm]"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="'1.18.4'"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="Calling kubeadm '[init --apiserver-advertise-address=192.168.179.61 --config=/var/lib/kubic-control/multi-master/kubeadm-config.yaml]'"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="Executing /usr/bin/kubeadm: [kubeadm init --apiserver-advertise-address=192.168.179.61 --config=/var/lib/kubic-control/multi-master/kubeadm-config.yaml]"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=error msg="Error invoking kubeadm: exit status 1\ncan not mix '--config' with arguments [apiserver-advertise-address]\nTo see the stack trace of this error execute with --v=5 or higher\n"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="Executing /usr/bin/kubeadm: [kubeadm reset --force]"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="[preflight] Running pre-flight checks\n[reset] No etcd config found. Assuming external etcd\n[reset] Please, manually reset etcd to prevent further issues\n[reset] Stopping the kubelet service\n[reset] Unmounting mounted directories in \"/var/lib/kubelet\"\n[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]\n[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]\n[reset] Deleting contents of stateful directories: [/var/lib/kubelet /var/lib/dockershim /var/run/kubernetes /var/lib/cni]\n\nThe reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d\n\nThe reset process does not reset or clean up iptables rules or IPVS tables.\nIf you wish to reset iptables, you must do so manually by using the \"iptables\" command.\n\nIf your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)\nto reset your system's IPVS tables.\n\nThe reset process does not clean your kubeconfig files and you must remove them manually.\nPlease, check the contents of the $HOME/.kube/config file.\n"
Jul 16 13:12:08 kubic-m1 kubicd[2070]: time="2020-07-16T13:12:08Z" level=info msg="Executing /usr/bin/systemctl: [systemctl disable --now crio]"
```

maybe a problem with kubeadm 1.8.x. 

p.s.: actually `multi-master` with an ip address might work (also gcloud uses ip addresses for lb) I probably also need to wait for a new kubicctl release so I can add another SANS certificate, because the last time I couldn't add a second master because of failing certificates, I'm pretty sure that multi-master only allows DNS addresses.

**Comment by thkukuk** [comment]
On Thu, Jul 16, Schmitt Christian wrote:

> maybe a problem with kubeadm 1.8.x. actually multi-master with an ip address

A multi-master problem.

**Comment by schmitch** [comment]
@thkukuk btw. `--apiserver-cert-extra-sans`  also does not work with `--multi-master`.
btw. I'm on `0.10.1`. also I want to get kubic running with https://github.com/plunder-app/kube-vip because it solves so many problems.

this is already not easy, because the first command that kubicctl tries to do is `kubeadm reset --force`, so I can't put something in `/etc/kubernetes/manifests`.

what I did is basically copied `kube-vip.yaml` while running `Initialize Kubernetes control-plane`

**Comment by 0pendev** [comment]
Just out of curiosity why are you trying to use kube-vip instead of the kubic loadbalancer ?

**Comment by schmitch** [comment]
because kubic's loadbalancer is an external node and only a single node and it needs DNS. which I don't want to use. also it's for a smaller scale deployment so kube-vip is the right answer.

**Comment by 0pendev** [comment]
Okay thanks. I did not know about kube-vip and I wasn't seing the use case ^^

**Comment by thkukuk** [comment]
Should work with v0.10.2 as far as I could test.
