### ISSUE TITLE
on new install, kubicctl fails

### ISSUE THREAD

**Issue by birdiesanders** [thkukuk/kubic-control#25]
It complains that it was unable to invoke kubeadm. I am not sure what to do at this point. Last year, this was a very, very easy thing to accomplish. Something has broken somewhere.

**Comment by thkukuk** [comment]
Please check the journal of the machine where kubicd is running. There should be an error message (journalctl -u kubicd).
Without the error message it's impossible to look at this.

**Comment by birdiesanders** [comment]
It turns out I forgot to bump the CPU count up on the VM. I will close.
