### ISSUE TITLE
Unable to setup HA-cluster

### ISSUE THREAD

**Issue by WilliWichtel** [thkukuk/kubic-control#31]
Since a couple of days I try to set up an HA-cluster including HA-proxy. I followed the README but I always fail.
I also made a post in the opensuse-forum: https://forums.opensuse.org/showthread.php/553350-Kubic-Cluster-Setup-fails

Are my steps correct and there are bugs in the Kubic-release, or is my way of setting up wrong?

**Comment by thkukuk** [comment]
Works fine for me, no problems or warnings at all following the documentation and setting up the haproxy via salt, too.

Did you let kubicctl/kubicd setup your haproxy via salt or did you create the config yourself?
Did you always use the right names (salt names must not be identical with DNS names, salt-keys -L will show you the salt names)?
Any errors from haproxy on the load balancer?

**Comment by WilliWichtel** [comment]
The problem was, that Kubic did not set the entered NTP-Server. Instead it used the pool.opensuse.org. But this was blocked by the firewall. So after adding an node, I run into certificate troubles and lost the whole setup.
