### ISSUE TITLE
Unable to add node, exits with `ERRO[0060] could not initialize: rpc error: code = DeadlineExceeded desc = context deadline exceeded`

### ISSUE THREAD

**Issue by kaotika** [thkukuk/kubic-control#5]
Hi, I'am testing out Kubic to dive into Kubernetes using these instructions: https://en.opensuse.org/Kubic:KubicD_and_kubicctl

* I installed a Kubic Admin Node and a Kubic Worker Node (`linux-3ks2`) with VirtualBox.
Both VMs are connected with a Host-Only Adapter.
* After installation I simply added the hostnames into the `/etc/hosts` file for DNS resolution.
* `kubicctl init` on the master worked properly
* adding the worker as minion also worked like expected (salt commands are fully functional)
* When I try to add the worker node `kubicctl node add linux-3ks2` the command fails after a minute with the following message:

```
ERRO[0060] could not initialize: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

How can I debug the process to track down the issue?

**Comment by thkukuk** [comment]
journalctl gives you the full output.

My first guess would be: there is a problem with the system time on the VMs, they are not in sync.

**Comment by kaotika** [comment]
Thanks,

you're guess was correct, but it was only one point.
Still I don't have an external DNS service, the host could not resolve its own hostname.
Additionally I added multiple network devices. The first one was a NAT device, the second the VPN. During `kubicctl init` the app choose the NAT device to advertise the kubernetes services. This could not work.

I choose to fully reinstall both VMs and set fixed `hostnames` (`kubic-master1` and `kubic-worker1`) during installation (click on the network settings in the setup summary).
Is there an option to add the hostname automatically to the hosts file during installation?

Even if it wasn't a explicit kubicctl problem, the steps I've done for everyone:

* on kubic-master1
```bash
tee /etc/hosts << EOF
127.0.1.1    kubic-master1
192.168.56.101   kubic-worker1
EOF

transactional-update pkg install ntp
# reboot
systemctl enable ntpd.service
systemctl start ntpd.service
```

* on kubic-worker1
```bash
tee /etc/hosts << EOF
127.0.1.1    kubic-worker1
192.168.56.100   kubic-master1
EOF

transactional-update pkg install ntp
# reboot
systemctl enable ntpd.service
systemctl start ntpd.service
```

**Update:**
Thanks for the resolution hint:

```bash
tee /etc/hosts << EOF
192.168.56.100   kubic-worker1
192.168.56.101   kubic-master1
EOF
```

**Comment by thkukuk** [comment]
kubernetes requires static, local routeable IP addresses and hostnames, which are resolveable. Else kubernetes (including kubeadm) will not work.

"127.0.1.1    kubic-worker1" is a really bad idea, the name should point to the IP, which is reacheable in the whole cluster. I'm pretty sure, that your master will not be able to reach kubic-worker1 via 127.0.1.1 and the other way around.

**Comment by thkukuk** [comment]
I have added some of the kubernetes requirements on the Kubicd wiki page:
https://en.opensuse.org/Kubic:KubicD_and_kubicctl#Requirements
