### ISSUE TITLE
kubicctl init fails with missing /var/lib/kubelet/config.yaml file

### ISSUE THREAD

**Issue by xadagaras** [thkukuk/kubic-control#7]
Hey there,

I have a fresh installation of openSUSE kubic with the Kubic Admin Node systemrole selected as it has been written inside of the docs for the master node.

When I try to run the command 
`kubicctl init` 

I get the following result

```
Initializing kubernetes master can take several minutes, please be patient.
Setting up single-master kubernetes node with weave
Initialize Kubernetes control-plane
Error invoking kubeadm: exit status 1
```

Inside of the logs I get the cause of this which is something like
``` 
Mar 04 19:14:50 localhost kubelet[3593]: F0304 19:14:50.702454    3593 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/>
Mar 04 19:14:50 localhost systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 04 19:14:50 localhost systemd[1]: kubelet.service: Failed with result 'exit-code'.
``` 

Since I am new to kubic, I have no idea what the problem is or if there is a bug.

I have tried a transactional-upgrade of my system but this did not fix the issue.

I've used the config as found here: https://github.com/thkukuk/kubic-control/tree/master/etc/kubicd which has been mentioned in this guide: https://en.opensuse.org/Kubic:KubicD_and_kubicctl

**Comment by thkukuk** [comment]
There error message is "Error invoking kubeadm", not "kubelet". Please look at the host, where kubicd is running, with journalctl for the reason kubeadm fails.

My guess is, it is this bug why kubeadm fails, ip_forward is disabled:
https://bugzilla.suse.com/show_bug.cgi?id=1163328

**Comment by xadagaras** [comment]
I have only one machine and kubelet is the only error I can find in journalctl

**Comment by thkukuk** [comment]
Since kubicd tried to execute kubeadm, there must be a line which contains kubeadm and ends with an error. If you use the error filtering of journalctl, could be that this does not match.

But for Kubernetes you need at least three hosts, you cannot do that with one machine only. MiniKube is an exception there.

**Comment by thkukuk** [comment]
No further comments
