### ISSUE TITLE
Add a way to specify a FDQN to add to the certs

### ISSUE THREAD

**Issue by user-name-is-taken** [thkukuk/kubic-control#9]
To access the cluster's management plane from another network you need to specify an FDQN to connect to. When connecting to the management plane's fdqn over https, your certs won't work unless you have the fdqn in the certs.

To solve this issue, I ran [these kubeadm steps](https://stackoverflow.com/questions/46360361/invalid-x509-certificate-for-kubernetes-master/54664423#54664423). Unfortunately, those steps leave old networking configurations behind as they say in their output:

```
The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.
```

So if there's a way to specify this fdqn in kubicctl it would be great because I wouldn't have to do this extra step. I see `kubicctl init`'s `--adv-addr` and `kubicctl certificates`. Is there a clean way to specify the fdqn that I'm not seeing?

Here's a full blog post about how to do this https://blog.scottlowe.org/2019/07/30/adding-a-name-to-kubernetes-api-server-certificate/

**Comment by thkukuk** [comment]
In short: you wanted to be able to specify the arguments for "--apiserver-cert-extra-sans".

**Comment by user-name-is-taken** [comment]
yes

**Comment by thkukuk** [comment]
I think this pull request could solve your problem: https://github.com/thkukuk/kubic-control/pull/15
